/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef THEFORGOTTENSERVER_PRIVATE_H
#define THEFORGOTTENSERVER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.3.6.3429"
#define VER_MAJOR	0
#define VER_MINOR	3
#define VER_RELEASE	6
#define VER_BUILD	3429
#define COMPANY_NAME	"Matheus - Toledo"
#define FILE_VERSION	"BETA"
#define FILE_DESCRIPTION	"Poke Supremo"
#define INTERNAL_NAME	"Poke Supremo"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Poke Supremo.exe"
#define PRODUCT_NAME	"Poke Supremo"
#define PRODUCT_VERSION	"1.5.1"

#endif /*THEFORGOTTENSERVER_PRIVATE_H*/
